spring:
  datasource:
    password: P@$$word1234!
    url: jdbc:mysql://localhost:3306/simulationdb
    username: db_user
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true
